# Setup
title: Xu
SEOTitle: 徐梦滢的博客 | Xu Blog
description: welcome my blog!
url: https://reset0514.github.io
avatar: /tx.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: xumengying
  card: summary
logo: logo.png
social:
  name: xumengying
  links:
  
    - https://github.com/reset0514
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx
disqus: xumengying

  

# Specify the author for blog posts
author:
  name: xumengying
  url: https://github.com/reset0514/
  email: 2484227928@qq.com
